apiVersion: v1
kind: Secret
metadata:
  annotations:
{{- with .Values.annotationsCommon }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    account-id: "123113232352"
    argocd.argoproj.io/secret-type: "cluster"
    account-name: "piktochart"
    account-type: "staging"
    region: "eu-central-1"
    cluster-type: "external"
    k8s-version: "1.25"
  name: piktochart-staging
type: Opaque
stringData:
  config: |
    {
      "bearerToken": "{{ index .Values "piktochart" "staging" "bearerToken" }}",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "caData"
      }
    }

