apiVersion: v1
kind: Pod
metadata:
  namespace: infra
spec:
  serviceAccountName: kaniko
  containers:
    - name: deployer
      image: 310830963532.dkr.ecr.eu-central-1.amazonaws.com/jenkins-deployer:2022-08-02-211051
      imagePullPolicy: IfNotPresent
      tty: true
