- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
- name: set system hostname
  command: hostnamectl set-hostname {{ inventory_hostname }}
- name: Add IPs to /etc/hosts on master and workers
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: Turn swap off
  shell: swapoff -a

- name: Set Enforce
  command: setenforce 0
  ignore_errors: true
- name: Disable SELinux
  selinux:
    state: disabled
  ignore_errors: true
- name : create a iptables file 
  file: 
    path: "/etc/modules-load.d/k8s.conf"
    state: "touch"
- name: letting ipTables see bridged networks
  blockinfile: 
    path: "/etc/modules-load.d/k8s.conf"
    block: | 
          br_netfilter
- name: Create the .conf file to load the modules at bootup
  file: 
    path: "/etc/modules-load.d/crio.conf"
    state: "touch"
- name: Set system configurations for Kubernetes networking
  file: 
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    state: "touch"
- name: Set up required sysctl params, these persist across reboots
  blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1
- name: Install kubelet package
  become: yes
  yum:
    name: kubelet
    enablerepo: kubernetes
  notify: restart kubelet
  ignore_errors: true

- name: Install kubectl package
  become: yes
  yum:
    name: kubectl
    enablerepo: kubernetes
  ignore_errors: true

- name: Install kubeadm package
  become: yes
  yum:
    name: kubeadm
    enablerepo: kubernetes
  ignore_errors: true

- name: Add vm swappiness
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'vm.swappiness = 0'
    state: present
    create: yes

- name: Add vm overcommit_memory
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'vm.overcommit_memory = 1'
    state: present
    create: yes

- name: Add netbridge config ip4
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    state: present
    create: yes
- name: Fix slowness of pulling images from AWS ECR 
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.ipv4.tcp_mtu_probing=1'
    state: present
    create: yes

- name: Increase net ipv4 tcp_max_syn_backlog
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.ipv4.tcp_max_syn_backlog=2621440'
    state: present
    create: yes

- name: update sysctl
  command: sysctl --system
- name: Stop Firewlld 
  systemd: 
    state: stopped
    name: firewalld 
    enabled: no 
  ignore_errors: true